"""add daily_digests table

Revision ID: 253461f785fb
Revises: f025ea4ece81
Create Date: 2026-09-25 23:16:23.169494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253461f785fb'
down_revision: Union[str, Sequence[str], None] = 'f025ea4ece81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_digests_digest_date'), 'daily_digests', ['digest_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_digests_digest_date'), table_name='daily_digests')
    op.drop_table('daily_digests')
    # ### end Alembic commands ###
