"""add structured_data to notes

Revision ID: 2b6157c39855
Revises: 921cb5048ea4
Create Date: 2026-09-26 00:17:07.446200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6157c39855'
down_revision: Union[str, Sequence[str], None] = '921cb5048ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('structured_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'structured_data')
    # ### end Alembic commands ###
