"""add goals table and task goal_id

Revision ID: 921cb5048ea4
Revises: 253461f785fb
Create Date: 2026-09-25 23:46:17.612261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921cb5048ea4'
down_revision: Union[str, Sequence[str], None] = '253461f785fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_parent_id'), 'goals', ['parent_id'], unique=False)
    op.add_column('tasks', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_goal_id'), 'tasks', ['goal_id'], unique=False)
    op.create_foreign_key('fk_tasks_goal_id_goals', 'tasks', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_goal_id_goals', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_goal_id'), table_name='tasks')
    op.drop_column('tasks', 'goal_id')
    op.drop_index(op.f('ix_goals_parent_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
