"""add hot_topics table

Revision ID: e195c2c9d4d3
Revises: 2b6157c39855
Create Date: 2026-09-26 00:36:03.248862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e195c2c9d4d3'
down_revision: Union[str, Sequence[str], None] = '2b6157c39855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hot_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_date', sa.Date(), nullable=False),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hot_topics_topic_date'), 'hot_topics', ['topic_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hot_topics_topic_date'), table_name='hot_topics')
    op.drop_table('hot_topics')
    # ### end Alembic commands ###
